version: "3"
services:
  elastic-agent:
    image: docker.elastic.co/beats/elastic-agent:8.1.3
    container_name: elastic-agent
    restart: always
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    environment:
      - FLEET_SERVER_ENABLE=true
      - FLEET_SERVER_ELASTICSEARCH_HOST=https://192.168.0.107:9200
      - FLEET_SERVER_SERVICE_TOKEN=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NjIwNDcwNzEwNjM6aHhOOVhHbXBUcnlDYU5sVEVhRlRYUQ
      - FLEET_SERVER_INSECURE_HTTP=1
      - FLEET_ENROLL_INSECURE=1
      - FLEET_SERVER_ELASTICSEARCH_CA=/home/eagent-dc/ca.crt
    volumes:
      - /home/saksham/Documents/eagent-dc:/home/eagent-dc
    ports:
      - 8220:8220
volumes:
  certs:
    driver: local
